### ISSUE TITLE
请求字段必须UrlEncode

### ISSUE THREAD

**Issue by coderge** [abcdlzy/PHPProxy#2]
url参数的值为https://github.com时会报Not Acceptable，只有UrlEncode为https%3a%2f%2fgithub.com才可以正常返回

**Comment by abcdlzy** [comment]
不好意思，现在才有空处理这个问题
这个问题我用firefox测试没有问题，能麻烦提供下出现问题的浏览器版本及操作系统版本么，谢谢

**Comment by coderge** [comment]
> 不好意思，现在才有空处理这个问题
> 这个问题我用firefox测试没有问题，能麻烦提供下出现问题的浏览器版本及操作系统版本么，谢谢

Chrome 51.0.2687.0
Windows NT 10.0

**Comment by DemoCap** [comment]
302被跳转，怎么办？
